# Generated by Django 5.2.6 on 2025-09-18 13:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intercorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data_ocorrencia', models.DateTimeField(help_text='Data e hora em que a intercorrência ocorreu', verbose_name='Data e Hora da Ocorrência')),
                ('user_username', models.CharField(db_index=True, help_text='Username do usuário que está registrando a ocorrência', max_length=150, verbose_name='Username do Usuário')),
                ('unidade_codigo_eol', models.CharField(db_index=True, help_text='Código EOL da unidade onde ocorreu a intercorrência', max_length=6, verbose_name='Código EOL da Unidade')),
                ('dre_codigo_eol', models.CharField(db_index=True, help_text='Código EOL da DRE responsável pela unidade', max_length=6, verbose_name='Código EOL da DRE')),
                ('sobre_furto_roubo_invasao_depredacao', models.BooleanField(default=False, verbose_name='É sobre furto, roubo, invasão ou depredação?')),
            ],
            options={
                'ordering': ('-criado_em',),
            },
        ),
    ]
