# Generated by Marcelo Alves on 2025-10-15

from django.db import migrations

def criar_tipos_iniciais(apps, schema_editor):
    tipo_ocorrencia_model = apps.get_model("intercorrencias", "TipoOcorrencia")

    tipos = [
        "Agressão física",
        "Ameaça interna",
        "Ameaça externa",
        "Ataque violento",
        "Desentendimento",
        "Ocorrência com objeto sem ameaça (arma de fogo, arma branca, etc)",
        "Dano material",
        "Depredação ou vandalismo",
        "Roubo",
        "Furto",
        "Invasão",
        "Ocorrência com veículo",
        "Outra",
    ]

    for nome in tipos:
        tipo_ocorrencia_model.objects.get_or_create(nome=nome)


class Migration(migrations.Migration):

    dependencies = [
        ("intercorrencias", "0002_tipoocorrencia"),
    ]

    operations = [
        migrations.RunPython(criar_tipos_iniciais),
    ]
