# Generated by Django 5.2.6 on 2025-10-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0003_popular_tipos_ocorrencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercorrencia',
            name='descricao_ocorrencia',
            field=models.TextField(blank=True, help_text='Descreva o fato ocorrido, incluindo informações sobre agressores, vítimas e prejuízos.', verbose_name='Descrição da Ocorrência'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='smart_sampa_situacao',
            field=models.CharField(blank=True, choices=[('sim_com_dano', 'Sim e houve dano'), ('sim_sem_dano', 'Sim, mas não houve dano'), ('nao_faz_parte', 'A UE não faz parte do Smart Sampa')], max_length=20, verbose_name='UE é contemplada pelo Smart Sampa? Houve dano às câmeras?'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='status',
            field=models.CharField(choices=[('em_preenchimento_diretor', 'Em preenchimento - Diretor')], default='em_preenchimento_diretor', max_length=30, verbose_name='Status da Intercorrência'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='tipos_ocorrencia',
            field=models.ManyToManyField(blank=True, help_text='Selecione um ou mais tipos de ocorrência', to='intercorrencias.tipoocorrencia', verbose_name='Tipos de Ocorrência'),
        ),
    ]
