# Generated by Django 5.2.6 on 2025-10-29 12:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0004_intercorrencia_descricao_ocorrencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declarante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('declarante', models.CharField(max_length=100, unique=True, verbose_name='Declarante')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Declarante',
                'verbose_name_plural': 'Declarantes',
            },
        ),
    ]
