# Generated by Django 5.2.6 on 2025-10-29 12:34

from django.db import migrations

def criar_declarantes(apps, schema_editor):
    declarante = apps.get_model('intercorrencias', 'Declarante')

    declarantes = [
        "Gabinete DRE",
        "GCM",
        "GIPE",
        "NAAPA",
        "Unidade Educacional"
    ]
    for nome in declarantes:
        declarante.objects.get_or_create(declarante=nome)

class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0005_declarante'),
    ]

    operations = [
        migrations.RunPython(criar_declarantes),
    ]