# Generated by Django 5.2.6 on 2025-10-29 19:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0006_popula_declarantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envolvido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('perfil_dos_envolvidos', models.CharField(max_length=30, unique=True, verbose_name='Envolvidos')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Envolvido',
                'verbose_name_plural': 'Envolvidos',
            },
        ),
    ]
