# Generated by Marcelo Alves on 2025-10-29

from django.db import migrations

def criar_envolvidos(apps, schema_editor):
    envolvido_model = apps.get_model("intercorrencias", "Envolvido")
    opcoes = [
        "Apenas um estudante",
        "Mais de um estudante",
        "Estudante e funcionários",
        "Funcionários",
        "Familiares",
        "Pessoas externas",
    ]
    for perfil_dos_envolvidos in opcoes:
        envolvido_model.objects.get_or_create(perfil_dos_envolvidos=perfil_dos_envolvidos, defaults={"ativo": True})


class Migration(migrations.Migration):

    dependencies = [
        ("intercorrencias", "0007_envolvido"),
    ]

    operations = [
        migrations.RunPython(criar_envolvidos),
    ]
