# Generated by Django 5.2.6 on 2025-11-03 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0008_add_envolvidos_iniciais'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercorrencia',
            name='comunicacao_seguranca_publica',
            field=models.CharField(blank=True, choices=[('sim_gcm', 'Sim, com GCM'), ('sim_pm', 'Sim, com a PM'), ('nao', 'Não')], max_length=20, verbose_name='Houve comunicação com a segurança pública?'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='declarante',
            field=models.ForeignKey(blank=True, help_text='Selecione quem está declarando a intercorrência', null=True, on_delete=django.db.models.deletion.PROTECT, to='intercorrencias.declarante', verbose_name='Quem é o declarante'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='protocolo_acionado',
            field=models.CharField(blank=True, choices=[('ameaca', 'Ameaça'), ('alerta', 'Alerta'), ('registro', 'Apenas para registro/ não se aplica')], max_length=20, verbose_name='Qual protocolo foi acionado?'),
        ),
    ]
