# Generated by Django 5.2.6 on 2025-11-03 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0009_intercorrencia_comunicacao_seguranca_publica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercorrencia',
            name='envolvido',
            field=models.ForeignKey(blank=True, help_text='Selecione quem são os envolvidos', null=True, on_delete=django.db.models.deletion.PROTECT, to='intercorrencias.envolvido', verbose_name='Quem são os envolvidos?'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='tem_info_agressor_ou_vitima',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, verbose_name='Existem informações sobre o agressor e/ou vítima?'),
        ),
    ]
