# Generated by Django 5.2.6 on 2025-11-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0010_intercorrencia_envolvido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercorrencia',
            name='acompanhado_naapa',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='A ocorrência foi acompanhada pelo NAAPA?'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='bairro',
            field=models.CharField(blank=True, help_text='Bairro do endereço da ocorrência', max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='cep',
            field=models.CharField(blank=True, help_text='CEP do endereço relacionado à intercorrência', max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='cidade',
            field=models.CharField(blank=True, help_text='Cidade onde ocorreu a intercorrência', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='complemento',
            field=models.CharField(blank=True, help_text='Complemento do endereço (ex: bloco, apartamento, referência)', max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='estado',
            field=models.CharField(blank=True, help_text='Nome do estado por extenso (ex: São Paulo, Rio de Janeiro)', max_length=50, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='etapa_escolar',
            field=models.CharField(blank=True, choices=[('edu_infantil_cei', 'Educação infantil - CEI'), ('edu_infantil_emei', 'Educação Infantil - EMEI'), ('fundamental_alfabetizacao', 'Ensino fundamental - Ciclo de alfabetização'), ('fundamental_autoral', 'Ensino fundamental - Ciclo Autoral'), ('ensino_medio', 'Ensino médio'), ('nao_se_aplica', 'Não se aplica')], max_length=27, verbose_name='Qual etapa escolar?'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='frequencia_escolar',
            field=models.CharField(blank=True, choices=[('regularizada', 'Regularizada'), ('inferior_75', 'Inferior a 75%'), ('inferior_50', 'Inferior a 50%'), ('sem_frequencia', 'Sem frequência'), ('transferido_dre', 'Transferido para outra DRE'), ('transferido_estadual', 'Transferido para a rede estadual'), ('transferido_particular', 'Transferido para rede particular'), ('nao_se_aplica', 'Não se aplica')], max_length=23, verbose_name='Qual a frequência escolar?'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='genero_pessoa_agressora',
            field=models.CharField(blank=True, choices=[('mulher_trans', 'Mulher trans'), ('homem_trans', 'Homem trans'), ('mulher_cis', 'Mulher cisgênero'), ('homem_cis', 'Homem cisgênero'), ('pessoa_nao_binaria', 'Pessoa não binária')], max_length=18, verbose_name='Qual gênero?'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='grupo_etnico_racial',
            field=models.CharField(blank=True, choices=[('amarelo', 'Amarelo'), ('branco', 'Branco'), ('indigena', 'Indígena'), ('preto', 'Preto'), ('pardo', 'Pardo')], max_length=8, verbose_name='Qual grupo étnico-racial?'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='idade_pessoa_agressora',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Qual a idade da pessoa agressora?'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='interacao_ambiente_escolar',
            field=models.TextField(blank=True, verbose_name='Como é a interação da pessoa agressora no ambiente escolar?'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='logradouro',
            field=models.CharField(blank=True, help_text='Rua, avenida ou local da ocorrência', max_length=255, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='motivacao_ocorrencia',
            field=models.CharField(blank=True, choices=[('bullying', 'Bullying'), ('cyberbullying', 'Cyberbullying'), ('atividades_ilicitas', 'Envolvimento com atividades ilícitas'), ('homofobia', 'Homofobia'), ('ideologias_extremistas', 'Ideologias extremistas (facista, nazista, discurso de ódio)'), ('misoginia_machismo', 'Misoginia/machismo'), ('racismo', 'Racismo'), ('violencia_genero', 'Violência de Gênero'), ('capacitismo', 'Capacitismo'), ('relacoes_afetivas', 'Relações afetivas'), ('uso_drogas', 'Uso de drogas'), ('vinganca', 'Vingança'), ('xenofobia', 'Xenofobia'), ('outros', 'Outros')], max_length=23, verbose_name='O que motivou a ocorrência?'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='nome_pessoa_agressora',
            field=models.CharField(blank=True, max_length=200, verbose_name='Qual o nome da pessoa agressora?'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='notificado_conselho_tutelar',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='A ocorrência foi notificada ao Conselho Tutelar?'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='numero_residencia',
            field=models.CharField(blank=True, help_text='Número do imóvel onde ocorreu a intercorrência', max_length=10, verbose_name='Número da residência'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='redes_protecao_acompanhamento',
            field=models.TextField(blank=True, verbose_name='Quais redes de proteção estão acompanhando o caso?'),
        ),
    ]
