# Generated by Django 5.2.6 on 2025-11-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0011_intercorrencia_acompanhado_naapa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercorrencia',
            name='acionamento_seguranca_publica',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Houve acionamento da Secretaria de Segurança Pública ou Forças de Segurança?'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='info_complementar_cpca',
            field=models.TextField(blank=True, verbose_name='Informação complementar da atuação conjunta entre DRE e CPCA'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='info_complementar_naapa',
            field=models.TextField(blank=True, verbose_name='Informação complementar da atuação conjunta entre DRE e NAAPA'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='info_complementar_sts',
            field=models.TextField(blank=True, verbose_name='Informação complementar da atuação conjunta entre DRE e STS'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='info_complementar_supervisao_escolar',
            field=models.TextField(blank=True, verbose_name='Informação complementar da atuação conjunta entre DRE e Supervisão Escolar'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='interlocucao_cpca',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Houve interlocução com a Coordenação de Políticas para Criança e Adolescente (CPCA)?'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='interlocucao_naapa',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Houve interlocução com o Núcleo de Apoio e Acompanhamento para a Aprendizagem (NAAPA)?'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='interlocucao_sts',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Houve interlocução com a Supervisão Técnica de Saúde (STS)?'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='interlocucao_supervisao_escolar',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Houve interlocução com a Supervisão Escolar?'),
        ),
    ]
