# Generated by Django 5.2.6 on 2025-11-15 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0012_intercorrencia_acionamento_seguranca_publica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intercorrencia',
            name='motivacao_ocorrencia',
        ),
    ]
