# Generated by Django 5.2.6 on 2025-11-15 13:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0013_remove_intercorrencia_motivacao_ocorrencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercorrencia',
            name='motivacao_ocorrencia',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('bullying', 'Bullying'), ('cyberbullying', 'Cyberbullying'), ('atividades_ilicitas', 'Envolvimento com atividades ilícitas'), ('homofobia', 'Homofobia'), ('ideologias_extremistas', 'Ideologias extremistas (facista, nazista, discurso de ódio)'), ('misoginia_machismo', 'Misoginia/machismo'), ('racismo', 'Racismo'), ('violencia_genero', 'Violência de Gênero'), ('capacitismo', 'Capacitismo'), ('relacoes_afetivas', 'Relações afetivas'), ('uso_drogas', 'Uso de drogas'), ('vinganca', 'Vingança'), ('xenofobia', 'Xenofobia'), ('outros', 'Outros')], max_length=23), blank=True, default=list, help_text='Selecione uma ou mais motivações', size=None, verbose_name='O que motivou a ocorrência?'),
        ),
    ]
