# Generated by Django 5.2.6 on 2025-11-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0014_intercorrencia_motivacao_ocorrencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercorrencia',
            name='finalizado_diretor_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finalizado pelo Diretor em'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='finalizado_diretor_por',
            field=models.CharField(blank=True, max_length=150, verbose_name='Finalizado pelo Diretor por'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='motivo_encerramento_ue',
            field=models.TextField(blank=True, verbose_name='Motivo do encerramento pela UE'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='protocolo_da_intercorrencia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Protocolo da Intercorrência'),
        ),
        migrations.AlterField(
            model_name='intercorrencia',
            name='status',
            field=models.CharField(choices=[('em_preenchimento_diretor', 'Em preenchimento - Diretor'), ('enviado_para_dre', 'Enviado para DRE')], default='em_preenchimento_diretor', max_length=30, verbose_name='Status da Intercorrência'),
        ),
    ]
