# Generated by Django 5.2.6 on 2025-11-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0015_intercorrencia_finalizado_diretor_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercorrencia',
            name='finalizado_dre_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finalizado DRE em'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='finalizado_dre_por',
            field=models.CharField(blank=True, max_length=150, verbose_name='Finalizado DRE por'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='motivo_encerramento_dre',
            field=models.TextField(blank=True, verbose_name='Motivo do encerramento DRE'),
        ),
        migrations.AlterField(
            model_name='intercorrencia',
            name='status',
            field=models.CharField(choices=[('em_preenchimento_diretor', 'Em preenchimento - Diretor'), ('enviado_para_dre', 'Enviado para DRE'), ('enviado_para_gipe', 'Enviado para GIPE')], default='em_preenchimento_diretor', max_length=30, verbose_name='Status da Intercorrência'),
        ),
    ]
