# Generated by Django 5.2.6 on 2025-12-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0016_intercorrencia_finalizado_dre_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercorrencia',
            name='ameaca_realizada_qual_maneira',
            field=models.CharField(blank=True, choices=[('presencialmente', 'Presencialmente'), ('virtualmente', 'Virtualmente')], max_length=15, verbose_name='Ameaça foi realizada de qual maneira?'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='encaminhamentos_gipe',
            field=models.TextField(blank=True, verbose_name='São informações após a análise feita pelo GIPE.'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='envolve_arma_ataque',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, verbose_name='Envolve arma ou ataque?'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='info_sobre_interacoes_virtuais_pessoa_agressora',
            field=models.TextField(blank=True, verbose_name='Existe informações sobre as interações virtuais da pessoa agressora?'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='qual_ciclo_aprendizagem',
            field=models.CharField(blank=True, choices=[('alfabetizacao', 'Alfabetização (1º ao 3º ano)'), ('interdisciplinar', 'Interdisciplinar (4º ao 6º ano)'), ('autoral', 'Autoral (7º ao 9º ano)')], max_length=17, verbose_name='Qual o ciclo de aprendizagem?'),
        ),
    ]
