# Generated by Django 5.2.6 on 2025-12-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0017_intercorrencia_ameaca_realizada_qual_maneira_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercorrencia',
            name='finalizado_gipe_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finalizado GIPE em'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='finalizado_gipe_por',
            field=models.CharField(blank=True, max_length=150, verbose_name='Finalizado GIPE por'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='motivo_encerramento_gipe',
            field=models.TextField(blank=True, verbose_name='Motivo do encerramento GIPE'),
        ),
        migrations.AlterField(
            model_name='intercorrencia',
            name='status',
            field=models.CharField(choices=[('em_preenchimento_diretor', 'Em preenchimento - Diretor'), ('enviado_para_dre', 'Enviado para DRE'), ('enviado_para_gipe', 'Enviado para GIPE'), ('finalizada', 'Finalizada')], default='em_preenchimento_diretor', max_length=30, verbose_name='Status da Intercorrência'),
        ),
    ]
