# Generated by Django 5.2.6 on 2026-02-19 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0018_intercorrencia_finalizado_gipe_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intercorrencia',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='intercorrencia',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='intercorrencia',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='intercorrencia',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='intercorrencia',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='intercorrencia',
            name='idade_pessoa_agressora',
        ),
        migrations.RemoveField(
            model_name='intercorrencia',
            name='logradouro',
        ),
        migrations.RemoveField(
            model_name='intercorrencia',
            name='nome_pessoa_agressora',
        ),
        migrations.RemoveField(
            model_name='intercorrencia',
            name='numero_residencia',
        ),
    ]
