# Generated by Django 5.2.6 on 2026-02-19 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0019_remove_intercorrencia_bairro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intercorrencia',
            name='motivo_encerramento_dre',
        ),
        migrations.RemoveField(
            model_name='intercorrencia',
            name='motivo_encerramento_gipe',
        ),
        migrations.RemoveField(
            model_name='intercorrencia',
            name='motivo_encerramento_ue',
        ),
    ]
