# Generated by Django 5.2.6 on 2026-02-20 14:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0020_remove_intercorrencia_motivo_encerramento_dre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaAgressora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da pessoa agressora')),
                ('idade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Idade da pessoa agressora')),
                ('intercorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas_agressoras', to='intercorrencias.intercorrencia', verbose_name='Intercorrência')),
            ],
            options={
                'verbose_name': 'Pessoa Agressora',
                'verbose_name_plural': 'Pessoas Agressoras',
                'ordering': ['nome'],
            },
        ),
    ]
