# Generated by Django 5.2.6 on 2026-02-23 13:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0020_remove_intercorrencia_motivo_encerramento_dre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercorrencia',
            name='etapa_escolar',
            field=models.CharField(blank=True, choices=[('edu_infantil_cei', 'Educação infantil - CEI'), ('edu_infantil_emei', 'Educação Infantil - EMEI'), ('fundamental_alfabetizacao', 'Ensino fundamental - Ciclo de alfabetização'), ('interdisciplinar', 'Ensino fundamental - Ciclo Interdisciplinar'), ('fundamental_autoral', 'Ensino fundamental - Ciclo Autoral'), ('ensino_medio', 'Ensino médio'), ('eja', 'Educação de Jovens e Adultos'), ('nao_se_aplica', 'Não se aplica')], max_length=27, verbose_name='Qual etapa escolar?'),
        ),
        migrations.AlterField(
            model_name='intercorrencia',
            name='genero_pessoa_agressora',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=18, verbose_name='Qual gênero?'),
        ),
        migrations.AlterField(
            model_name='intercorrencia',
            name='motivacao_ocorrencia',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('bullying', 'Bullying'), ('cyberbullying', 'Cyberbullying'), ('atividades_ilicitas', 'Envolvimento com atividades ilícitas'), ('bullying_homofobia', 'Bullying/Homofobia'), ('ideologias_extremistas', 'Ideologias extremistas (facista, nazista, discurso de ódio)'), ('bullying_misoginia', 'Bullying/Misoginia'), ('bullying_machismo', 'Bullying/machismo'), ('bullying_racismo', 'Bullying/Racismo'), ('violencia_genero', 'Violência de Gênero'), ('bullying_capacitismo', 'Bullying/Capacitismo'), ('relacoes_afetivas', 'Relações afetivas'), ('uso_drogas', 'Uso de drogas'), ('vinganca', 'Vingança'), ('bullying_xenofobia', 'Bullying/Xenofobia'), ('outros', 'Outros')], max_length=23), blank=True, default=list, help_text='Selecione uma ou mais motivações', size=None, verbose_name='O que motivou a ocorrência?'),
        ),
    ]
