# Generated by Django 5.2.6 on 2026-02-23 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0021_alter_intercorrencia_etapa_escolar_and_more'),
        ('intercorrencias', '0021_pessoaagressora'),
    ]

    operations = [
    ]
