# Generated by Django 5.2.6 on 2026-02-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0022_merge_20260223_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoocorrencia',
            name='tipo_formulario',
            field=models.CharField(choices=[('PATRIMONIAL', 'Patrimonial'), ('GERAL', 'Geral'), ('TODOS', 'Todos')], default='TODOS', max_length=20, verbose_name='Tipo de Formulário'),
        ),
        migrations.AlterField(
            model_name='intercorrencia',
            name='smart_sampa_situacao',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=20, verbose_name='UE é contemplada pelo Smart Sampa?'),
        ),
    ]
