# Generated by Django 5.2.6 on 2026-02-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0023_tipoocorrencia_tipo_formulario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercorrencia',
            name='comunicacao_seguranca_publica',
            field=models.CharField(blank=True, choices=[('sim_gcm', 'Sim, com GCM'), ('sim_pm', 'Sim, com a PM'), ('sim_dc', 'Sim, com a Defesa civil'), ('sim_cbm', 'Sim, com o Bombeiro'), ('nao', 'Não')], max_length=20, verbose_name='Houve comunicação com a segurança pública?'),
        ),
    ]
