# Generated by Django 5.2.6 on 2026-03-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0024_alter_intercorrencia_comunicacao_seguranca_publica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intercorrencia',
            name='envolvido',
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='envolvido',
            field=models.ManyToManyField(blank=True, help_text='Selecione quem são os envolvidos', to='intercorrencias.envolvido', verbose_name='Quem são os envolvidos?'),
        ),
    ]
