# Generated by Django 5.2.6 on 2026-03-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0025_remove_intercorrencia_envolvido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intercorrencia',
            name='etapa_escolar',
        ),
        migrations.RemoveField(
            model_name='intercorrencia',
            name='frequencia_escolar',
        ),
        migrations.RemoveField(
            model_name='intercorrencia',
            name='genero_pessoa_agressora',
        ),
        migrations.RemoveField(
            model_name='intercorrencia',
            name='grupo_etnico_racial',
        ),
        migrations.RemoveField(
            model_name='intercorrencia',
            name='interacao_ambiente_escolar',
        ),
        migrations.AddField(
            model_name='pessoaagressora',
            name='etapa_escolar',
            field=models.CharField(blank=True, choices=[('edu_infantil_cei', 'Educação infantil - CEI'), ('edu_infantil_emei', 'Educação Infantil - EMEI'), ('fundamental_alfabetizacao', 'Ensino fundamental - Ciclo de alfabetização'), ('interdisciplinar', 'Ensino fundamental - Ciclo Interdisciplinar'), ('fundamental_autoral', 'Ensino fundamental - Ciclo Autoral'), ('ensino_medio', 'Ensino médio'), ('eja', 'Educação de Jovens e Adultos'), ('nao_se_aplica', 'Não se aplica')], max_length=27, verbose_name='Qual etapa escolar?'),
        ),
        migrations.AddField(
            model_name='pessoaagressora',
            name='frequencia_escolar',
            field=models.CharField(blank=True, choices=[('regularizada', 'Regularizada'), ('inferior_75', 'Inferior a 75%'), ('inferior_50', 'Inferior a 50%'), ('sem_frequencia', 'Sem frequência'), ('transferido_dre', 'Transferido para outra DRE'), ('transferido_estadual', 'Transferido para a rede estadual'), ('transferido_particular', 'Transferido para rede particular'), ('nao_se_aplica', 'Não se aplica')], max_length=23, verbose_name='Qual a frequência escolar?'),
        ),
        migrations.AddField(
            model_name='pessoaagressora',
            name='genero',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=18, verbose_name='Qual gênero?'),
        ),
        migrations.AddField(
            model_name='pessoaagressora',
            name='grupo_etnico_racial',
            field=models.CharField(blank=True, choices=[('amarelo', 'Amarelo'), ('branco', 'Branco'), ('indigena', 'Indígena'), ('preto', 'Preto'), ('pardo', 'Pardo')], max_length=8, verbose_name='Qual grupo étnico-racial?'),
        ),
        migrations.AddField(
            model_name='pessoaagressora',
            name='interacao_ambiente_escolar',
            field=models.TextField(blank=True, verbose_name='Como é a interação da pessoa no ambiente escolar?'),
        ),
    ]
