# Generated by Django 5.2.6 on 2026-03-12 15:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0026_remove_intercorrencia_etapa_escolar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intercorrencia',
            name='qual_ciclo_aprendizagem',
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='envolvido_outros',
            field=models.TextField(blank=True, help_text='Descreva quem são os envolvidos.', verbose_name='Outros envolvidos'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='etapa_escolar',
            field=models.CharField(blank=True, choices=[('edu_infantil_cei', 'Educação infantil - CEI'), ('edu_infantil_emei', 'Educação Infantil - EMEI'), ('fundamental_alfabetizacao', 'Ensino fundamental - Ciclo de alfabetização'), ('interdisciplinar', 'Ensino fundamental - Ciclo Interdisciplinar'), ('fundamental_autoral', 'Ensino fundamental - Ciclo Autoral'), ('ensino_medio', 'Ensino médio'), ('eja', 'Educação de Jovens e Adultos'), ('mova', 'Movimento de Alfabetização de Jovens e Adultos - MOVA'), ('nao_se_aplica', 'Não se aplica')], max_length=27, verbose_name='Qual etapa escolar?'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='motivacao_ocorrencia_outros',
            field=models.TextField(blank=True, help_text='Descreva qual foi a motivação.', verbose_name='Outra motivação da ocorrência'),
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='tipos_ocorrencia_outros',
            field=models.TextField(blank=True, help_text='Descreva qual é o tipo de ocorrência.', verbose_name='Outros tipos de ocorrência'),
        ),
        migrations.AlterField(
            model_name='intercorrencia',
            name='motivacao_ocorrencia',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('bullying', 'Bullying'), ('cyberbullying', 'Cyberbullying'), ('atividades_ilicitas', 'Envolvimento com atividades ilícitas'), ('bullying_homofobia', 'Bullying/Homofobia'), ('ideologias_extremistas', 'Ideologias extremistas (facista, nazista, discurso de ódio)'), ('bullying_misoginia', 'Bullying/Misoginia'), ('bullying_machismo', 'Bullying/Machismo'), ('bullying_racismo', 'Bullying/Racismo'), ('violencia_genero', 'Violência de Gênero'), ('bullying_capacitismo', 'Bullying/Capacitismo'), ('relacoes_afetivas', 'Relações afetivas'), ('uso_drogas', 'Uso de drogas'), ('uso_alcool', 'Uso de álcool'), ('vinganca', 'Vingança'), ('bullying_xenofobia', 'Bullying/Xenofobia'), ('outros', 'Outros')], max_length=23), blank=True, default=list, help_text='Selecione uma ou mais motivações', size=None, verbose_name='O que motivou a ocorrência?'),
        ),
        migrations.AlterField(
            model_name='pessoaagressora',
            name='etapa_escolar',
            field=models.CharField(blank=True, choices=[('edu_infantil_cei', 'Educação infantil - CEI'), ('edu_infantil_emei', 'Educação Infantil - EMEI'), ('fundamental_alfabetizacao', 'Ensino fundamental - Ciclo de alfabetização'), ('interdisciplinar', 'Ensino fundamental - Ciclo Interdisciplinar'), ('fundamental_autoral', 'Ensino fundamental - Ciclo Autoral'), ('ensino_medio', 'Ensino médio'), ('eja', 'Educação de Jovens e Adultos'), ('mova', 'Movimento de Alfabetização de Jovens e Adultos - MOVA'), ('nao_se_aplica', 'Não se aplica')], max_length=27, verbose_name='Qual etapa escolar?'),
        ),
    ]
