# Generated by Django 5.2.6 on 2026-03-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0027_remove_intercorrencia_qual_ciclo_aprendizagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercorrencia',
            name='fora_horario_funcionamento_ue',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='A ocorrência aconteceu fora do horario de funcionamento da UE?'),
        ),
    ]
