# Generated by Django 5.2.6 on 2026-03-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0028_intercorrencia_fora_horario_funcionamento_ue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercorrencia',
            name='comunicacao_seguranca_publica',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=20, verbose_name='A segurança pública foi comunicada?'),
        ),
    ]
