# Generated by Django 5.2.6 on 2026-03-27 13:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0029_alter_intercorrencia_comunicacao_seguranca_publica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intercorrencia',
            name='envolvido_outros',
        ),
        migrations.RemoveField(
            model_name='intercorrencia',
            name='motivacao_ocorrencia_outros',
        ),
        migrations.RemoveField(
            model_name='intercorrencia',
            name='tipos_ocorrencia_outros',
        ),
        migrations.AlterField(
            model_name='intercorrencia',
            name='motivacao_ocorrencia',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('bullying', 'Bullying'), ('bullying_capacitismo', 'Bullying/Capacitismo'), ('bullying_homofobia', 'Bullying/Homofobia'), ('bullying_machismo', 'Bullying/Machismo'), ('bullying_misoginia', 'Bullying/Misoginia'), ('bullying_racismo', 'Bullying/Racismo'), ('bullying_xenofobia', 'Bullying/Xenofobia'), ('cyberbullying', 'Cyberbullying'), ('atividades_ilicitas', 'Envolvimento com atividades ilícitas'), ('ideologias_extremistas', 'Ideologias extremistas (discurso de ódio)'), ('relacoes_afetivas', 'Relações afetivas'), ('uso_alcool', 'Uso de álcool'), ('uso_drogas', 'Uso de drogas'), ('vinganca', 'Vingança'), ('violencia_genero', 'Violência de Gênero')], max_length=23), blank=True, default=list, help_text='Selecione uma ou mais motivações', size=None, verbose_name='O que motivou a ocorrência?'),
        ),
    ]
