# Generated by Django 5.2.6 on 2026-03-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0030_remove_intercorrencia_envolvido_outros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoocorrencia',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descreva o tipo de ocorrência, para que ele possa ser identificado e diferenciado dos outros tipos.', verbose_name='Descrição do tipo de ocorrência'),
        ),
    ]
