# Generated by Django 5.2.6 on 2026-03-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0031_tipoocorrencia_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intercorrencia',
            name='acompanhado_naapa',
        ),
        migrations.RemoveField(
            model_name='intercorrencia',
            name='redes_protecao_acompanhamento',
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='ocorrencia_acompanhada_pelo',
            field=models.CharField(blank=True, choices=[('naapa', 'NAAPA'), ('comissao_mediacao_conflitos', 'Comissão de Mediação de Conflitos'), ('supervisao_escolar', 'Supervisão Escolar'), ('cefai', 'CEFAI')], max_length=30, verbose_name='A ocorrência está sendo acompanhada por'),
        ),
        migrations.AddField(
            model_name='pessoaagressora',
            name='nacionalidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='A nacionalidade corresponde ao país de nascimento.'),
        ),
        migrations.AddField(
            model_name='pessoaagressora',
            name='pessoa_com_deficiencia',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Pessoa com deficiência?'),
        ),
        migrations.AlterField(
            model_name='intercorrencia',
            name='notificado_conselho_tutelar',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='A ocorrência foi notificada ao CT (Conselho Tutelar?)'),
        ),
        migrations.AlterField(
            model_name='pessoaagressora',
            name='grupo_etnico_racial',
            field=models.CharField(blank=True, choices=[('amarela', 'Amarela'), ('branca', 'Branca'), ('indigena', 'Indígena'), ('preta', 'Preta'), ('parda', 'Parda'), ('nao_declarada', 'Não declarada')], max_length=15, verbose_name='Qual grupo étnico-racial?'),
        ),
    ]
