# Generated by Django 5.2.6 on 2026-04-02 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0032_remove_intercorrencia_acompanhado_naapa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intercorrencia',
            name='info_sobre_interacoes_virtuais_pessoa_agressora',
        ),
    ]
