# Generated by Django 5.2.6 on 2026-04-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0033_remove_intercorrencia_info_sobre_interacoes_virtuais_pessoa_agressora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intercorrencia',
            name='info_complementar_cpca',
        ),
        migrations.RemoveField(
            model_name='intercorrencia',
            name='info_complementar_naapa',
        ),
        migrations.RemoveField(
            model_name='intercorrencia',
            name='info_complementar_sts',
        ),
        migrations.RemoveField(
            model_name='intercorrencia',
            name='info_complementar_supervisao_escolar',
        ),
        migrations.RemoveField(
            model_name='intercorrencia',
            name='interlocucao_cpca',
        ),
        migrations.RemoveField(
            model_name='intercorrencia',
            name='interlocucao_naapa',
        ),
        migrations.RemoveField(
            model_name='intercorrencia',
            name='interlocucao_sts',
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='nr_processo_sei',
            field=models.CharField(blank=True, max_length=25, verbose_name='Numero do processo SEI'),
        ),
        migrations.AlterField(
            model_name='intercorrencia',
            name='acionamento_seguranca_publica',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='A ronda escolar foi acionada?'),
        ),
        migrations.AlterField(
            model_name='intercorrencia',
            name='interlocucao_supervisao_escolar',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='A supervisão escolar foi comunicada?'),
        ),
    ]
