# Generated by Django 5.2.6 on 2026-04-06 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0034_remove_intercorrencia_info_complementar_cpca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intercorrencia',
            name='ocorrencia_acompanhada_pelo',
        ),
    ]
