# Generated by Django 5.2.6 on 2026-04-06 16:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0035_remove_intercorrencia_ocorrencia_acompanhada_pelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercorrencia',
            name='ocorrencia_acompanhada_pelo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('naapa', 'NAAPA'), ('comissao_mediacao_conflitos', 'Comissão de Mediação de Conflitos'), ('supervisao_escolar', 'Supervisão Escolar'), ('cefai', 'CEFAI')], max_length=30), blank=True, default=list, size=None, verbose_name='A ocorrência está sendo acompanhada por'),
        ),
        migrations.AddField(
            model_name='pessoaagressora',
            name='idade_em_meses',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='A idade está em meses?'),
        ),
    ]
