# Generated by Django 5.2.6 on 2026-04-17 12:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0036_intercorrencia_ocorrencia_acompanhada_pelo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intercorrencia',
            name='acionamento_seguranca_publica',
        ),
        migrations.RemoveField(
            model_name='intercorrencia',
            name='interlocucao_supervisao_escolar',
        ),
        migrations.AddField(
            model_name='intercorrencia',
            name='quais_orgaos_acionados_dre',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('comunicacao_supervisao_tecnica_saude', 'Comunicação com Supervisão Técnica de Saúde'), ('comunicacao_assistencia_social', 'Comunicação com Assistência Social'), ('comunicacao_gcm_ronda_escolar', 'Comunicação com GCM/Ronda Escolar'), ('comunicacao_gipe', 'Comunicação com GIPE')], max_length=40), blank=True, default=list, size=None, verbose_name='Quais órgãos foram acionados pela DRE'),
        ),
    ]
