# Generated by Django 5.2.6 on 2026-04-17 19:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0037_remove_intercorrencia_acionamento_seguranca_publica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercorrencia',
            name='motivacao_ocorrencia',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('capacitismo', 'Capacitismo'), ('conflitos_afetivos', 'Conflitos afetivos'), ('atividades_ilicitas', 'Envolvimento com atividades ilícitas'), ('homofobia', 'Homofobia'), ('ideologias_extremistas', 'Ideologias extremistas (discurso de ódio)'), ('machismo', 'Machismo'), ('misoginia', 'Misoginia'), ('racismo', 'Racismo'), ('uso_alcool', 'Uso de álcool'), ('uso_drogas', 'Uso de drogas'), ('vinganca', 'Vingança'), ('violencia_genero', 'Violência de Gênero'), ('xenofobia', 'Xenofobia')], max_length=23), blank=True, default=list, help_text='Selecione uma ou mais motivações', size=None, verbose_name='O que motivou a ocorrência?'),
        ),
        migrations.AlterField(
            model_name='intercorrencia',
            name='ocorrencia_acompanhada_pelo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('naapa', 'NAAPA'), ('comissao_mediacao_conflitos', 'Comissão de Mediação de Conflitos'), ('supervisao_escolar', 'Supervisão Escolar'), ('cefai', 'CEFAI'), ('vara_da_infancia', 'Vara da infância')], max_length=30), blank=True, default=list, size=None, verbose_name='A ocorrência está sendo acompanhada por'),
        ),
    ]
