# Generated by Django 5.2.6 on 2026-04-27 13:47

from django.db import migrations


def popula_declarante(apps, schema_editor):
    declarante_model = apps.get_model('intercorrencias', 'Declarante')

    declarantes = [
        "Diretor(a)",
        "AD (Assistente de diretor)",
        "GIPE",
        "Gabinete DRE",
    ]

    for nome in declarantes:
        declarante_model.objects.get_or_create(
            declarante=nome,
            defaults={
                "ativo": True,
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0038_alter_intercorrencia_motivacao_ocorrencia_and_more'),
    ]

    operations = [
        migrations.RunPython(popula_declarante),
    ]