# Generated by Django 5.2.6 on 2026-04-27 13:53

from django.db import migrations


def popula_envolvido(apps, schema_editor):
    envolvido_model = apps.get_model('intercorrencias', 'Envolvido')

    envolvidos = [
        "Monitores",
        "Entre estudantes",
        "Diretor",
        "Colaborador da terceirizada",
        "Diretor/Assistente de diretor",
        "Estagiários",
        "Pessoas externas",
        "Familiares",
        "Funcionários",
        "Estudante e funcionário",
        "Um estudante",
    ]

    for nome in envolvidos:
        envolvido_model.objects.get_or_create(
            perfil_dos_envolvidos=nome,
            defaults={
                "ativo": True,
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0039_popula_declarante'),
    ]

    operations = [
        migrations.RunPython(popula_envolvido),
    ]