# Generated by Django 5.2.6 on 2026-04-27 13:54

from django.db import migrations


def popula_tipo_ocorrencia(apps, schema_editor):
    tipo_ocorrencia_model = apps.get_model('intercorrencias', 'TipoOcorrencia')

    dados = [
        {"nome": "Cyberbullying", "defaults": {"tipo_formulario": "GERAL", "descricao": "Bullying realizado por meios digitais, como redes sociais, mensagens ou aplicativos.", "ativo": True}},
        {"nome": "Bullying", "defaults": {"tipo_formulario": "GERAL", "descricao": "Comportamento repetitivo de intimidação, humilhação ou exclusão de uma pessoa.", "ativo": True}},
        {"nome": "Homicídio", "defaults": {"tipo_formulario": "GERAL", "descricao": "Situação em que ocorre a morte de uma pessoa, causada por terceiros.", "ativo": True}},
        {"nome": "Suicídio", "defaults": {"tipo_formulario": "GERAL", "descricao": "Situação em que ocorre a morte de uma pessoa, causada por ela mesma.", "ativo": True}},
        {"nome": "Ocorrência com câmera/smart sampa", "defaults": {"tipo_formulario": "PATRIMONIAL", "descricao": "Problemas ou incidentes relacionados ao sistema de monitoramento, como falhas, danos, mau funcionamento ou uso indevido das câmeras.", "ativo": True}},
        {"nome": "Desastres climáticos", "defaults": {"tipo_formulario": "PATRIMONIAL", "descricao": "Eventos naturais que impactam a unidade, como enchentes, alagamentos, quedas de árvores, vendavais ou deslizamentos.", "ativo": True}},
        {"nome": "Ocorrência com veículo", "defaults": {"tipo_formulario": "PATRIMONIAL", "descricao": "Incidentes envolvendo veículos dentro ou no entorno da unidade, como colisões, danos, uso indevido ou situações suspeitas.", "ativo": True}},
        {"nome": "Invasão", "defaults": {"tipo_formulario": "PATRIMONIAL", "descricao": "Entrada não autorizada de pessoas na unidade escolar, com ou sem intenção de causar danos ou cometer outras infrações.", "ativo": True}},
        {"nome": "Furto", "defaults": {"tipo_formulario": "PATRIMONIAL", "descricao": "Subtração de bens sem uso de violência ou ameaça, geralmente de forma discreta ou sem percepção imediata.", "ativo": True}},
        {"nome": "Roubo", "defaults": {"tipo_formulario": "PATRIMONIAL", "descricao": "Subtração de bens com uso de ameaça, violência ou intimidação.", "ativo": True}},
        {"nome": "Depredação ou vandalismo", "defaults": {"tipo_formulario": "PATRIMONIAL", "descricao": "Ações intencionais de destruição, pichação ou deterioração do patrimônio da unidade escolar.", "ativo": True}},
        {"nome": "Dano material", "defaults": {"tipo_formulario": "PATRIMONIAL", "descricao": "Prejuízos físicos causados à estrutura, equipamentos ou bens da unidade, de forma acidental ou intencional.", "ativo": True}},
        {"nome": "Ocorrência com objeto sem ameaça (arma de fogo, arma branca, etc)", "defaults": {"tipo_formulario": "GERAL", "descricao": "Envolvimento de objetos que poderiam ser perigosos (arma de fogo, arma branca, etc.), mas sem ameaça ou ataque direto.", "ativo": True}},
        {"nome": "Ataque violento", "defaults": {"tipo_formulario": "GERAL", "descricao": "Ação agressiva com intenção de causar ferimentos graves ou risco de vida.", "ativo": True}},
        {"nome": "Ameaça externa", "defaults": {"tipo_formulario": "GERAL", "descricao": "Situação de ameaça feita por alguém de fora da unidade educacional.", "ativo": True}},
        {"nome": "Ameaça interna", "defaults": {"tipo_formulario": "GERAL", "descricao": "Situação de ameaça feita por alguém dentro da unidade educacional.", "ativo": True}},
        {"nome": "Agressão física", "defaults": {"tipo_formulario": "GERAL", "descricao": "Qualquer ação que cause dano físico a outra pessoa, como empurrões, socos ou chutes.", "ativo": True}},
    ]

    for item in dados:
        tipo_ocorrencia_model.objects.get_or_create(
            nome=item["nome"],
            defaults=item["defaults"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0040_popula_envolvido'),
    ]

    operations = [
        migrations.RunPython(popula_tipo_ocorrencia),
    ]