# Generated by Django 5.2.6 on 2026-08-18 10:00

from django.db import migrations


def popula_tipo_ocorrencia(apps, schema_editor):
    tipo_ocorrencia_model = apps.get_model('intercorrencias', 'TipoOcorrencia')

    tipo_ocorrencia_model.objects.get_or_create(
        nome="Agressão verbal",
        defaults={
            "tipo_formulario": "GERAL",
            "descricao": "Uso de palavras para ofender, humilhar ou ameaçar alguém.",
            "ativo": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('intercorrencias', '0041_popula_tipo_ocorrencia'),
    ]

    operations = [
        migrations.RunPython(popula_tipo_ocorrencia),
    ]
